/* Generated by ion-compiler from tests/test_large_codegen_smoke.ion. Do not edit.
 * GNU C (GCC/Clang). Merged stdlib/import code may appear below. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include "ion_runtime.h"

typedef struct Vec_Payload0 {
    void* data;
    size_t len;
    size_t capacity;
    size_t elem_size;
} Vec_Payload0;

typedef struct Vec_int {
    void* data;
    size_t len;
    size_t capacity;
    size_t elem_size;
} Vec_int;

typedef struct tuple_ion_sender_t_ion_receiver_t {
    ion_sender_t f0;
    ion_receiver_t f1;
} tuple_ion_sender_t_ion_receiver_t;

typedef struct Payload0 {
    int id;
    int tag;
    Vec_int* data;
} Payload0;

typedef struct Payload1 {
    int id;
    int tag;
    Vec_int* data;
} Payload1;

typedef struct Payload2 {
    int id;
    int tag;
    Vec_int* data;
} Payload2;

typedef struct Payload3 {
    int id;
    int tag;
    Vec_int* data;
} Payload3;

typedef struct Payload4 {
    int id;
    int tag;
    Vec_int* data;
} Payload4;

typedef struct Payload5 {
    int id;
    int tag;
    Vec_int* data;
} Payload5;

typedef struct Payload6 {
    int id;
    int tag;
    Vec_int* data;
} Payload6;

typedef struct Payload7 {
    int id;
    int tag;
    Vec_int* data;
} Payload7;

typedef struct Payload8 {
    int id;
    int tag;
    Vec_int* data;
} Payload8;

typedef struct Payload9 {
    int id;
    int tag;
    Vec_int* data;
} Payload9;

typedef struct Payload10 {
    int id;
    int tag;
    Vec_int* data;
} Payload10;

typedef struct Payload11 {
    int id;
    int tag;
    Vec_int* data;
} Payload11;

typedef struct Payload12 {
    int id;
    int tag;
    Vec_int* data;
} Payload12;

typedef struct Payload13 {
    int id;
    int tag;
    Vec_int* data;
} Payload13;

typedef struct Payload14 {
    int id;
    int tag;
    Vec_int* data;
} Payload14;

typedef struct Payload15 {
    int id;
    int tag;
    Vec_int* data;
} Payload15;

typedef struct Payload16 {
    int id;
    int tag;
    Vec_int* data;
} Payload16;

typedef struct Payload17 {
    int id;
    int tag;
    Vec_int* data;
} Payload17;

typedef struct Payload18 {
    int id;
    int tag;
    Vec_int* data;
} Payload18;

typedef struct Payload19 {
    int id;
    int tag;
    Vec_int* data;
} Payload19;

typedef struct Payload20 {
    int id;
    int tag;
    Vec_int* data;
} Payload20;

typedef struct Payload21 {
    int id;
    int tag;
    Vec_int* data;
} Payload21;

typedef struct Payload22 {
    int id;
    int tag;
    Vec_int* data;
} Payload22;

typedef struct Payload23 {
    int id;
    int tag;
    Vec_int* data;
} Payload23;

typedef struct Payload24 {
    int id;
    int tag;
    Vec_int* data;
} Payload24;

typedef struct Payload25 {
    int id;
    int tag;
    Vec_int* data;
} Payload25;

typedef struct Payload26 {
    int id;
    int tag;
    Vec_int* data;
} Payload26;

typedef struct Payload27 {
    int id;
    int tag;
    Vec_int* data;
} Payload27;

typedef struct Payload28 {
    int id;
    int tag;
    Vec_int* data;
} Payload28;

typedef struct Payload29 {
    int id;
    int tag;
    Vec_int* data;
} Payload29;

typedef struct Payload30 {
    int id;
    int tag;
    Vec_int* data;
} Payload30;

typedef struct Payload31 {
    int id;
    int tag;
    Vec_int* data;
} Payload31;

typedef struct Payload32 {
    int id;
    int tag;
    Vec_int* data;
} Payload32;

typedef struct Payload33 {
    int id;
    int tag;
    Vec_int* data;
} Payload33;

typedef struct Payload34 {
    int id;
    int tag;
    Vec_int* data;
} Payload34;

typedef struct Payload35 {
    int id;
    int tag;
    Vec_int* data;
} Payload35;

typedef struct Payload36 {
    int id;
    int tag;
    Vec_int* data;
} Payload36;

typedef struct Payload37 {
    int id;
    int tag;
    Vec_int* data;
} Payload37;

typedef struct Payload38 {
    int id;
    int tag;
    Vec_int* data;
} Payload38;

typedef struct Payload39 {
    int id;
    int tag;
    Vec_int* data;
} Payload39;

typedef struct Option_Payload0 {
    int tag;
    union {
        struct {
            Payload0 arg0;
        } variant_0;
    } data;
} Option_Payload0;

typedef struct Option_int {
    int tag;
    union {
        struct {
            int arg0;
        } variant_0;
    } data;
} Option_int;

static void* ion_spawn_entry_0(void* arg);
typedef struct {
    ion_sender_t done_tx;
    ion_receiver_t job_rx;
} ion_spawn_ctx_0;

Payload0 build_payload(int id);
int main(void);
Payload0 build_payload(int id) {
    Payload0 ret_val = {0};
    Vec_int* data = ((Vec_int*)(ion_vec_new(sizeof(int))));
    ion_vec_push((ion_vec_t*)(data), &id, sizeof(int));
    ret_val = (Payload0){.id = id, .tag = (id * 2), .data = data};
    goto epilogue;
epilogue:
        return ret_val;
}

int main(void) {
    int ret_val = 0;
    ion_sender_t job_tx;
    ion_receiver_t job_rx;
    ion_channel_new(sizeof(int), 1, &job_tx, &job_rx);
    ion_sender_t done_tx;
    ion_receiver_t done_rx;
    ion_channel_new(sizeof(int), 1, &done_tx, &done_rx);
    {
        ion_spawn_ctx_0* ctx = (ion_spawn_ctx_0*)malloc(sizeof(ion_spawn_ctx_0));
        if (!ctx) { ion_panic("spawn allocation failed"); }
        ctx->done_tx = done_tx;
        done_tx = (ion_sender_t){0};
        ctx->job_rx = job_rx;
        job_rx = (ion_receiver_t){0};
        if (ion_spawn(ion_spawn_entry_0, ctx) != 0) { free(ctx); ion_panic("spawn failed"); }
    }
    { int _send_val = 0; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 1; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 2; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 3; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 4; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 5; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 6; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 7; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 8; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 9; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 10; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 11; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 12; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 13; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 14; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 15; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 16; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 17; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 18; ion_channel_send(&job_tx, &_send_val); }
    { int _send_val = 19; ion_channel_send(&job_tx, &_send_val); }
    Vec_Payload0* items = ((Vec_Payload0*)(ion_vec_new(sizeof(Payload0))));
    Payload0 built = build_payload(7);
    ion_vec_push((ion_vec_t*)(items), &built, sizeof(Payload0));
    ion_receiver_t done_rx_mut = done_rx;
    int total = ({ int tmp; ion_channel_recv(&done_rx_mut, &tmp); tmp; });
    if (total != 190) {
        ret_val = 1;
        if (done_rx_mut.channel) { ion_channel_handle_drop(done_rx_mut.channel); }
        if (items) { ion_vec_free((ion_vec_t*)(items)); }
        if (job_tx.channel) { ion_channel_handle_drop(job_tx.channel); }
        goto epilogue;
    }
    ret_val = 0;
    if (done_rx_mut.channel) { ion_channel_handle_drop(done_rx_mut.channel); }
    if (items) { ion_vec_free((ion_vec_t*)(items)); }
    if (job_tx.channel) { ion_channel_handle_drop(job_tx.channel); }
    goto epilogue;
epilogue:
        return ret_val;
}


static void* ion_spawn_entry_0(void* arg) {
    ion_spawn_ctx_0* ctx = (ion_spawn_ctx_0*)arg;
    if (!ctx) { ion_panic("spawn null context"); }
    ion_sender_t done_tx = ctx->done_tx;
    ion_receiver_t job_rx = ctx->job_rx;
    free(ctx);
    ion_receiver_t rx = job_rx;
    int sum = 0;
    int n = 0;
    while (n < 20) {
        sum = (sum + ({ int tmp; ion_channel_recv(&rx, &tmp); tmp; }));
        n = (n + 1);
    }
    { ion_channel_send(&done_tx, &sum); }
    if (rx.channel) { ion_channel_handle_drop(rx.channel); }
    if (done_tx.channel) { ion_channel_handle_drop(done_tx.channel); }
    goto spawn_0_epilogue;
spawn_0_epilogue:
    return NULL;
}

