/* Generated by ion-compiler from tests/test_trait_bound_copy_fn_ok.ion. Do not edit.
 * GNU C (GCC/Clang). Merged stdlib/import code may appear below. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include "ion_runtime.h"

int add_one(int x);
int main(void);
int (*identity_fn_int_ret_int(int (*value)(int)))(int);
int add_one(int x) {
    int ret_val = 0;
    ret_val = (x + 1);
    goto epilogue;
epilogue:
        return ret_val;
}

int main(void) {
    int ret_val = 0;
    int (*g)(int) = identity_fn_int_ret_int(add_one);
    ret_val = g(10);
    (void)g;
    goto epilogue;
epilogue:
        return ret_val;
}

int (*identity_fn_int_ret_int(int (*value)(int)))(int) {
    int (*ret_val)(int) = 0;
    ret_val = value;
    goto epilogue;
epilogue:
        return ret_val;
}

