/* Generated by ion-compiler from examples/text_summary/text_summary.ion. Do not edit.
 * GNU C (GCC/Clang). Merged stdlib/import code may appear below. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "ion_runtime.h"

typedef struct TextCounts {
    int lines;
    int words;
} TextCounts;

typedef struct ReadResult {
    int tag;
    union {
        struct {
            ion_string_t* arg0;
        } variant_0;
        struct {
            int arg0;
        } variant_1;
    } data;
} ReadResult;

static ReadResult ReadResult_Ok_new(ion_string_t* arg0) {
    ReadResult result = { .tag = 0, .data = { .variant_0 = { .arg0 = arg0 } } };
    return result;
}

static ReadResult ReadResult_Err_new(int arg0) {
    ReadResult result = { .tag = 1, .data = { .variant_1 = { .arg0 = arg0 } } };
    return result;
}

extern int write(int fd, uint8_t* buf, int count);

extern int open(uint8_t* path, int flags);
extern int read(int fd, uint8_t* buf, int count);
extern int close(int fd);

TextCounts summarize_text(ion_string_t* text);
int main(void);
void fmt_print_int(int n);
void fmt_println_int(int n);
ion_string_t* fmt_int_to_string(int n);
ReadResult fs_read_to_string_result(ion_string_t* path);
void io_print(ion_string_t* s);
void io_println(ion_string_t* s);
void io_print_str(uint8_t* s, int len);
void io_print_int(int n);
TextCounts summarize_text(ion_string_t* text) {
    TextCounts ret_val = {0};
    int lines = 0;
    int words = 0;
    int in_word = 0;
    ion_string_t* __for_container_389 = text;
    int __for_i_389 = 0;
    while (__for_i_389 < ((__for_container_389) ? (int)((__for_container_389)->len) : 0)) {
        uint8_t ch = ({ int __ion_idx_0 = __for_i_389; (__ion_idx_0 >= 0 && __ion_idx_0 < __for_container_389->len) ? __for_container_389->data[__ion_idx_0] : (ion_panic("String index out of bounds"), (uint8_t)0); });
        if (ch == 10) {
            lines = (lines + 1);
        }
        int is_space = ((((ch == 32) || (ch == 9)) || (ch == 10)) || (ch == 13));
        if (is_space) {
            in_word = 0;
        } else {
            if (!in_word) {
                words = (words + 1);
                in_word = 1;
            }
        }
        __for_step_389:
        __for_i_389 = (__for_i_389 + 1);
    }
    ret_val = (TextCounts){.lines = lines, .words = words};
    if (__for_container_389) { ion_string_free(__for_container_389); }
    goto epilogue;
epilogue:
        return ret_val;
}

int main(void) {
    int ret_val = 0;
    ion_string_t* path = ion_string_from_literal("sample.txt", 10);
    ReadResult match_val_0 = fs_read_to_string_result(path);
    switch (match_val_0.tag) {
        case 0: { // Ok
            ion_string_t* content = match_val_0.data.variant_0.arg0;
            ion_string_t* text = content;
            int bytes = ((text) ? (int)((text)->len) : 0);
            TextCounts counts = summarize_text(text);
            io_println(ion_string_from_literal("file: sample.txt", 16));
            io_println(fmt_int_to_string(counts.lines));
            io_println(fmt_int_to_string(counts.words));
            io_println(fmt_int_to_string(bytes));
            ret_val = 0;
            if (path) { ion_string_free(path); }
            goto epilogue;
            break;
        }
        case 1: { // Err
            int code = match_val_0.data.variant_1.arg0;
            io_print(ion_string_from_literal("read failed: ", 13));
            io_println(fmt_int_to_string(code));
            ret_val = 1;
            if (path) { ion_string_free(path); }
            goto epilogue;
            break;
        }
    }
    goto epilogue;
epilogue:
        return ret_val;
}

void fmt_print_int(int n) {
    io_print_int(n);
epilogue:
        return;
}

void fmt_println_int(int n) {
    io_print_int(n);
    {
        int _newline = write(1, "\n", 1);
    }
epilogue:
        return;
}

ion_string_t* fmt_int_to_string(int n) {
    ion_string_t* ret_val = 0;
    uint8_t buf[12] = {0};
    int len = 0;
    int negative = 0;
    int value = n;
    ion_string_t* result = ion_string_new();
    if (value == 0) {
        ret_val = ion_string_from_literal("0", 1);
        if (result) { ion_string_free(result); }
        goto epilogue;
    }
    if (value < 0) {
        negative = 1;
        if (value == (-2147483648)) {
            ret_val = ion_string_from_literal("-2147483648", 11);
            if (result) { ion_string_free(result); }
            goto epilogue;
        }
        value = (0 - value);
    }
    while (value > 0) {
        int digit = (value % 10);
        buf[len] = (uint8_t)(48 + digit);
        len = (len + 1);
        value = (value / 10);
    }
    if (negative) {
        ion_string_push_byte(result, (unsigned char)((uint8_t)45));
    }
    int i = (len - 1);
    while (i >= 0) {
        ion_string_push_byte(result, (unsigned char)(({ int __ion_idx_1 = i; (__ion_idx_1 >= 0 && __ion_idx_1 < 12) ? buf[__ion_idx_1] : (ion_panic("Array index out of bounds"), buf[0]); })));
        i = (i - 1);
    }
    ret_val = result;
    goto epilogue;
epilogue:
        return ret_val;
}

ReadResult fs_read_to_string_result(ion_string_t* path) {
    ReadResult ret_val = {0};
    {
        int fd = open(path->data, 0);
        if (fd < 0) {
            ret_val = ReadResult_Err_new((-1));
            goto epilogue;
        }
        ion_string_t* text = ion_string_new();
        uint8_t buf[256] = {0};
        int n = read(fd, &buf[0], 256);
        while (n > 0) {
            int i = 0;
            while (i < n) {
                ion_string_push_byte(text, (unsigned char)(buf[i]));
                i = (i + 1);
            }
            n = read(fd, &buf[0], 256);
        }
        if (n < 0) {
            int _closed = close(fd);
            ret_val = ReadResult_Err_new((-2));
            if (text) { ion_string_free(text); }
            goto epilogue;
        }
        int _closed = close(fd);
        ret_val = ReadResult_Ok_new(text);
        goto epilogue;
    }
    goto epilogue;
epilogue:
        return ret_val;
}

void io_print(ion_string_t* s) {
    {
        int _result = write(1, s->data, (int)s->len);
    }
epilogue:
        return;
}

void io_println(ion_string_t* s) {
    {
        int _result = write(1, s->data, (int)s->len);
        int _newline = write(1, "\n", 1);
    }
epilogue:
        return;
}

void io_print_str(uint8_t* s, int len) {
    if (len < 0) {
                goto epilogue;
    }
    {
        int _result = write(1, s, len);
    }
epilogue:
        return;
}

void io_print_int(int n) {
    uint8_t buf[12] = {0};
    int len = 0;
    int negative = 0;
    int value = n;
    if (value == 0) {
        {
            int _result = write(1, "0", 1);
        }
                goto epilogue;
    }
    if (value < 0) {
        negative = 1;
        if (value == (-2147483648)) {
            {
                int _result = write(1, "-2147483648", 11);
            }
                        goto epilogue;
        }
        value = (0 - value);
    }
    while (value > 0) {
        int digit = (value % 10);
        buf[len] = (uint8_t)(48 + digit);
        len = (len + 1);
        value = (value / 10);
    }
    int i = 0;
    while (i < (len / 2)) {
        uint8_t tmp = ({ int __ion_idx_2 = i; (__ion_idx_2 >= 0 && __ion_idx_2 < 12) ? buf[__ion_idx_2] : (ion_panic("Array index out of bounds"), buf[0]); });
        buf[i] = ({ int __ion_idx_3 = ((len - 1) - i); (__ion_idx_3 >= 0 && __ion_idx_3 < 12) ? buf[__ion_idx_3] : (ion_panic("Array index out of bounds"), buf[0]); });
        buf[((len - 1) - i)] = tmp;
        i = (i + 1);
    }
    if (negative) {
        {
            int _minus = write(1, "-", 1);
        }
    }
    {
        int _result = write(1, &buf[0], len);
    }
epilogue:
        return;
}

