/* Generated by ion-compiler from examples/channel_worker.ion. Do not edit.
 * GNU C (GCC/Clang). Merged stdlib/import code may appear below. */

#ifdef __GNUC__
#define ION_MAYBE_UNUSED __attribute__((unused))
#else
#define ION_MAYBE_UNUSED
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "ion_runtime.h"

static void* ion_spawn_entry_0(void* arg);
typedef struct {
    ion_sender_t done_tx;
    ion_receiver_t job_rx;
} ion_spawn_ctx_0;

typedef struct tuple_ion_sender_t_ion_receiver_t {
    ion_sender_t f0;
    ion_receiver_t f1;
} tuple_ion_sender_t_ion_receiver_t;

int job_count(void);
int main(void);
int job_count(void) {
    int ret_val = 0;
    ret_val = 5;
    goto epilogue;
epilogue:
        return ret_val;
}

int main(void) {
    int ret_val = 0;
    ion_sender_t job_tx;
    ion_receiver_t job_rx;
    ion_channel_new(sizeof(int), 1, &job_tx, &job_rx);
    ion_sender_t done_tx;
    ion_receiver_t done_rx;
    ion_channel_new(sizeof(int), 1, &done_tx, &done_rx);
    {
        ion_spawn_ctx_0* ctx = (ion_spawn_ctx_0*)malloc(sizeof(ion_spawn_ctx_0));
        if (!ctx) { ion_panic("spawn allocation failed"); }
        ctx->done_tx = done_tx;
        done_tx = (ion_sender_t){0};
        ctx->job_rx = job_rx;
        job_rx = (ion_receiver_t){0};
        if (ion_spawn(ion_spawn_entry_0, ctx) != 0) { free(ctx); ion_panic("spawn failed"); }
    }
    int next_job = 1;
    while (next_job <= job_count()) {
        { ion_channel_send(&job_tx, &next_job); }
        next_job = (next_job + 1);
    }
    ion_receiver_t done_rx_mut = done_rx;
    int total = ({ int tmp; ion_channel_recv(&done_rx_mut, &tmp); tmp; });
    if (total != 15) {
        ret_val = 1;
        if (done_rx_mut.channel) { ion_channel_handle_drop(done_rx_mut.channel); }
        if (job_tx.channel) { ion_channel_handle_drop(job_tx.channel); }
        goto epilogue;
    }
    ret_val = 0;
    goto epilogue;
epilogue:
        return ret_val;
}


static void* ion_spawn_entry_0(void* arg) {
    ion_spawn_ctx_0* ctx = (ion_spawn_ctx_0*)arg;
    if (!ctx) { ion_panic("spawn null context"); }
    ion_sender_t done_tx = ctx->done_tx;
    ion_receiver_t job_rx = ctx->job_rx;
    free(ctx);
    ion_receiver_t rx = job_rx;
    int sum = 0;
    int received = 0;
    while (1) {
        if (received >= job_count()) {
            break;
        }
        int job = ({ int tmp; ion_channel_recv(&rx, &tmp); tmp; });
        sum = (sum + job);
        received = (received + 1);
    }
    { ion_channel_send(&done_tx, &sum); }
    if (rx.channel) { ion_channel_handle_drop(rx.channel); }
    if (done_tx.channel) { ion_channel_handle_drop(done_tx.channel); }
    goto spawn_0_epilogue;
spawn_0_epilogue:
    return NULL;
}

