/* Generated by ion-compiler from examples/hello_world.ion. Do not edit.
 * GNU C (GCC/Clang). Merged stdlib/import code may appear below. */

#ifdef __GNUC__
#define ION_MAYBE_UNUSED __attribute__((unused))
#else
#define ION_MAYBE_UNUSED
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "ion_runtime.h"

extern int write(int fd, uint8_t* buf, int count);

int main(void);
int main(void) {
    int ret_val = 0;
    {
        int _result = write(1, (uint8_t*)"Hello, World!\n", 14);
        (void)_result;
    }
    ret_val = 0;
    goto epilogue;
epilogue:
        return ret_val;
}

