/* Generated by ion-compiler from examples/http_server.ion. Do not edit.
 * GNU C (GCC/Clang). Merged stdlib/import code may appear below. */

#ifdef __GNUC__
#define ION_MAYBE_UNUSED __attribute__((unused))
#else
#define ION_MAYBE_UNUSED
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "ion_runtime.h"

typedef struct SockAddrIn {
    uint16_t sin_family;
    uint16_t sin_port;
    uint32_t sin_addr;
    uint8_t sin_zero[8];
} SockAddrIn;

extern void ion_net_init(void);
extern int socket(int domain, int sock_type, int protocol);
extern int bind(int sockfd, SockAddrIn* addr, int addrlen);
extern int listen(int sockfd, int backlog);
extern int accept(int sockfd, uint8_t* addr, int* addrlen);
extern int recv_sys(int sockfd, uint8_t* buf, int len, int flags);
extern int send_sys(int sockfd, uint8_t* buf, int len, int flags);
extern int close(int fd);
extern uint16_t htons(uint16_t hostshort);

static void* ion_spawn_entry_0(void* arg);
typedef struct {
    int client_fd;
} ion_spawn_ctx_0;

SockAddrIn create_sockaddr_in(uint16_t ION_MAYBE_UNUSED port);
int handle_client(int ION_MAYBE_UNUSED client_fd);
void dispatch_client(int ION_MAYBE_UNUSED client_fd);
int main(void);
SockAddrIn create_sockaddr_in(uint16_t ION_MAYBE_UNUSED port) {
    SockAddrIn ret_val = {0};
    {
        ret_val = (SockAddrIn){.sin_family = 2, .sin_port = htons(port), .sin_addr = 0, .sin_zero = {0}};
        goto epilogue;
    }
    goto epilogue;
epilogue:
        return ret_val;
}

int handle_client(int ION_MAYBE_UNUSED client_fd) {
    int ret_val = 0;
    uint8_t buffer[128] = {0};
    {
        int received = recv_sys(client_fd, &buffer[0], 128, 0);
        if (received < 1) {
            close(client_fd);
            ret_val = 0;
            goto epilogue;
        }
        int _sent1 = send_sys(client_fd, (uint8_t*)"HTTP/1.1 200 OK\r\n", 17, 0);
        (void)_sent1;
        int _sent2 = send_sys(client_fd, (uint8_t*)"Content-Type: text/html\r\n", 25, 0);
        (void)_sent2;
        int _sent3 = send_sys(client_fd, (uint8_t*)"Content-Length: 89\r\n", 20, 0);
        (void)_sent3;
        int _sent4 = send_sys(client_fd, (uint8_t*)"Connection: close\r\n", 19, 0);
        (void)_sent4;
        int _sent5 = send_sys(client_fd, (uint8_t*)"\r\n", 2, 0);
        (void)_sent5;
        int _sent6 = send_sys(client_fd, (uint8_t*)"<html><head><title>Ion HTTP Server</title></head><body><h1>Hello from Ion!</h1><p>This is a simple HTTP server written in Ion.</p></body></html>", 89, 0);
        (void)_sent6;
        close(client_fd);
    }
    ret_val = 0;
    goto epilogue;
epilogue:
        return ret_val;
}

void dispatch_client(int ION_MAYBE_UNUSED client_fd) {
    if (client_fd < 0) {
                goto epilogue;
    }
    {
        ion_spawn_ctx_0* ctx = (ion_spawn_ctx_0*)malloc(sizeof(ion_spawn_ctx_0));
        if (!ctx) { ion_panic("spawn allocation failed"); }
        ctx->client_fd = client_fd;
        client_fd = 0;
        if (ion_spawn(ion_spawn_entry_0, ctx) != 0) { free(ctx); ion_panic("spawn failed"); }
    }
    goto epilogue;
epilogue:
        return;
}

int main(void) {
    int ret_val = 0;
    {
        ion_net_init();
        int af_inet = 2;
        int sock_stream = 1;
        int ipproto_tcp = 6;
        int server_fd = socket(af_inet, sock_stream, ipproto_tcp);
        if (server_fd < 0) {
            ret_val = 1;
            goto epilogue;
        }
        SockAddrIn sockaddr = create_sockaddr_in(8080);
        int bind_result = bind(server_fd, &sockaddr, 16);
        if (bind_result < 0) {
            close(server_fd);
            ret_val = 2;
            goto epilogue;
        }
        int listen_result = listen(server_fd, 10);
        if (listen_result < 0) {
            close(server_fd);
            ret_val = 3;
            goto epilogue;
        }
        uint8_t client_addr[16] = {0};
        int addrlen = 16;
        int client_fd = accept(server_fd, &client_addr[0], &addrlen);
        dispatch_client(client_fd);
        close(server_fd);
    }
    ret_val = 0;
    goto epilogue;
epilogue:
        return ret_val;
}


static void* ion_spawn_entry_0(void* arg) {
    ion_spawn_ctx_0* ctx = (ion_spawn_ctx_0*)arg;
    if (!ctx) { ion_panic("spawn null context"); }
    int client_fd = ctx->client_fd;
    free(ctx);
    int _result = handle_client(client_fd);
    (void)_result;
    goto spawn_0_epilogue;
spawn_0_epilogue:
    return NULL;
}

