/* Generated by ion-compiler from examples/minimal.ion. Do not edit.
 * GNU C (GCC/Clang). Merged stdlib/import code may appear below. */

#ifdef __GNUC__
#define ION_MAYBE_UNUSED __attribute__((unused))
#else
#define ION_MAYBE_UNUSED
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include "ion_runtime.h"

int main(void);
int main(void) {
    int ret_val = 0;
    int x = 10;
    int y = 20;
    int z = (x + y);
    ret_val = z;
    goto epilogue;
epilogue:
        return ret_val;
}

